# Generated by Django 4.1.5 on 2023-03-07 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('audience', models.CharField(choices=[('men', 'Для мужчин'), ('women', 'Для женщин'), ('all', 'Для всех')], max_length=6)),
                ('age_limits', models.CharField(choices=[('21+', '21+'), ('18+', '18+'), ('16+', '16+'), ('None', 'Без ограничений')], max_length=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('video', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('location_link', models.CharField(max_length=200)),
                ('contacts', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EventImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='media/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='event.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_dates', to='event.event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='hashtag',
            field=models.ManyToManyField(related_name='events', to='event.hashtag'),
        ),
        migrations.AddField(
            model_name='event',
            name='main_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_events', to='category.category'),
        ),
        migrations.AddField(
            model_name='event',
            name='side_category1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='side_events1', to='category.category'),
        ),
        migrations.AddField(
            model_name='event',
            name='side_category2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='side_events2', to='category.category'),
        ),
        migrations.AddField(
            model_name='event',
            name='side_category3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='side_events3', to='category.category'),
        ),
    ]
