# Generated by Django 4.1.5 on 2023-02-11 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age_limits', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('date_and_time', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('location_link', models.CharField(max_length=200)),
                ('contacts', models.CharField(max_length=50)),
                ('images', models.ImageField(upload_to='')),
                ('hashtag', models.ManyToManyField(related_name='events', to='event.hashtag')),
                ('main_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_events', to='category.category')),
                ('side_category1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='side_events1', to='category.category')),
                ('side_category2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='side_events2', to='category.category')),
                ('side_category3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='side_events3', to='category.category')),
            ],
        ),
    ]
