# Generated by Django 4.1.5 on 2023-03-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='age_limits',
            field=models.CharField(choices=[('1', '21+'), ('2', '18+'), ('3', '16+'), ('4', 'Без ограничений')], max_length=6),
        ),
        migrations.AlterField(
            model_name='event',
            name='audience',
            field=models.CharField(choices=[('1', 'Для мужчин'), ('2', 'Для женщин'), ('3', 'Для всех')], max_length=6),
        ),
    ]
