# Generated by Django 4.1.5 on 2023-02-13 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date_and_time',
        ),
    ]
