# Generated by Django 4.1.5 on 2023-04-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.AddField(
            model_name='event',
            name='type_of_location',
            field=models.CharField(choices=[('1', 'Бар'), ('2', 'Ресторан'), ('3', 'Кофейня'), ('4', 'Ночной клуб'), ('5', 'Концертный зал'), ('6', 'Театр'), ('7', 'Музей'), ('8', 'На улице'), ('9', 'Учебное заведение'), ('10', 'Торговый центр'), ('11', 'Кинотеатр'), ('12', 'Отель'), ('13', 'Коворкинг'), ('14', 'Караоке'), ('15', 'Кальянная'), ('16', 'Магазин'), ('17', 'Конференц-зал'), ('18', 'Спортивный зал'), ('19', 'Салон красоты'), ('20', 'Спа Центр'), ('21', 'Тойкана')], default=0, max_length=200),
            preserve_default=False,
        ),
    ]
