# Generated by Django 4.1.5 on 2023-04-09 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('event', '0003_event_type_of_location2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='main_category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, related_name='main_events', to='category.category'),
            preserve_default=False,
        ),
    ]
