# Generated by Django 4.1.5 on 2023-02-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_eventdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='images',
            field=models.CharField(max_length=200),
        ),
    ]
