# Generated by Django 4.1.5 on 2023-04-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_event_main_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tickets_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
