# Generated by Django 4.1.5 on 2023-04-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_event_tickets_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='poster',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
