# Generated by Django 4.1.5 on 2023-04-20 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_event_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='contacts',
        ),
    ]
