# Generated by Django 4.1.5 on 2023-02-13 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_remove_event_images_eventvideos_eventimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventvideos',
            old_name='image',
            new_name='video',
        ),
    ]
