# Generated by Django 4.1.5 on 2023-02-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_rename_image_eventvideos_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='age_limits',
        ),
        migrations.AddField(
            model_name='event',
            name='for_adults',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='for_kids',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
