# Generated by Django 4.1.5 on 2023-04-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('event', '0007_remove_event_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='main_category',
        ),
        migrations.RemoveField(
            model_name='event',
            name='side_category1',
        ),
        migrations.RemoveField(
            model_name='event',
            name='side_category2',
        ),
        migrations.AddField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(related_name='events', to='category.category'),
        ),
    ]
