# Generated by Django 4.1.5 on 2023-02-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_remove_event_age_limits_event_for_adults_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='free',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
