# Generated by Django 4.1.5 on 2023-04-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_alter_event_age_limits_alter_event_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
