# Generated by Django 4.1.5 on 2023-04-22 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_alter_event_poster'),
        ('event', '0010_event_image1_event_image2_event_image3_event_image4_and_more'),
    ]

    operations = [
    ]
