# Generated by Django 4.1.5 on 2023-04-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_merge_20230422_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
