# Generated by Django 4.1.5 on 2023-04-24 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0012_alter_event_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='age_limits',
            field=models.CharField(choices=[('Без ограничений', 'Без ограничений'), ('16+', '16+'), ('18+', '18+'), ('21+', '21+')], max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='audience',
            field=models.CharField(choices=[('Для всех', 'Для всех'), ('Для детей', 'Для детей'), ('Для женщин', 'Для женщин'), ('Для мужчин', 'Для мужчин')], max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='type_of_location',
            field=models.CharField(choices=[('Бар', 'Бар'), ('Ресторан', 'Ресторан'), ('Кофейня', 'Кофейня'), ('Ночной клуб', 'Ночной клуб'), ('Концертный зал', 'Концертный зал'), ('Театр', 'Театр'), ('Музей', 'Музей'), ('На улице', 'На улице'), ('Учебное заведение', 'Учебное заведение'), ('Торговый центр', 'Торговый центр'), ('Кинотеатр', 'Кинотеатр'), ('Отель', 'Отель'), ('Коворкинг', 'Коворкинг'), ('Караоке', 'Караоке'), ('Кальянная', 'Кальянная'), ('Магазин', 'Магазин'), ('Конференц-зал', 'Конференц-зал'), ('Спортивный зал', 'Спортивный зал'), ('Салон красоты', 'Салон красоты'), ('Спа Центр', 'Спа Центр'), ('Тойкана', 'Тойкана')], max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='type_of_location2',
            field=models.CharField(blank=True, choices=[('Бар', 'Бар'), ('Ресторан', 'Ресторан'), ('Кофейня', 'Кофейня'), ('Ночной клуб', 'Ночной клуб'), ('Концертный зал', 'Концертный зал'), ('Театр', 'Театр'), ('Музей', 'Музей'), ('На улице', 'На улице'), ('Учебное заведение', 'Учебное заведение'), ('Торговый центр', 'Торговый центр'), ('Кинотеатр', 'Кинотеатр'), ('Отель', 'Отель'), ('Коворкинг', 'Коворкинг'), ('Караоке', 'Караоке'), ('Кальянная', 'Кальянная'), ('Магазин', 'Магазин'), ('Конференц-зал', 'Конференц-зал'), ('Спортивный зал', 'Спортивный зал'), ('Салон красоты', 'Салон красоты'), ('Спа Центр', 'Спа Центр'), ('Тойкана', 'Тойкана')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='event.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
