# Generated by Django 4.1.5 on 2023-05-07 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_alter_ticket_event_alter_ticket_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='type_of_location2',
        ),
        migrations.AlterField(
            model_name='event',
            name='age_limits',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='age_limit', to='event.agelimit'),
        ),
        migrations.AlterField(
            model_name='event',
            name='audience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiences', to='event.audience'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type_of_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_of_location', to='event.location'),
        ),
    ]
