# Generated by Django 4.1.5 on 2023-05-07 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_agelimit_audience_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agelimit',
            old_name='limit',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='audience',
            old_name='audience',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='type',
            new_name='name',
        ),
    ]
