# Generated by Django 4.1.5 on 2023-05-08 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_rename_limit_agelimit_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='price',
        ),
    ]
