# Generated by Django 4.1.5 on 2023-05-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_remove_event_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price_from',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
