# Generated by Django 4.1.5 on 2023-05-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0021_event_price_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='price_from',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='price_to',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
