# Generated by Django 4.1.5 on 2023-05-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0022_alter_event_price_from_alter_event_price_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location_name',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='location_link',
            field=models.CharField(max_length=300),
        ),
    ]
