# Generated by Django 4.2.3 on 2024-01-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0024_event_event_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_language',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
