# Generated by Django 4.1.5 on 2023-04-11 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='phone_numer',
            new_name='phone_number',
        ),
    ]
